<a href="https://colab.research.google.com/github/raflinoob132/MachineLearning-1/blob/main/Week%202/CitarumWater/Collab%20Notebook/CitarumWater.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install mglearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, roc_curve, confusion_matrix, classification_report
)
from sklearn.impute import SimpleImputer

import mglearn

In [34]:
# Load dataset
url = "https://raw.githubusercontent.com/farrelrassya/teachingMLDL/refs/heads/main/01.%20Machine%20Learning/02.%20Week%202/Dataset/CitarumWater.csv"
df = pd.read_csv(url)

# 1. Hapus kolom yang tidak diperlukan
df = df.drop(['No', 'NamaSungai', 'Waktu', 'TitikPantau', 'O2'], axis=1)

# 2. Konversi kolom 'Temp' ke float
df['Temp'] = df['Temp'].str.replace('°C', '', regex=True).astype(float)

# 3. Hapus baris dengan NaN
df = df.dropna()
# 4. Pastikan tidak ada NaN tersisa
print("Jumlah NaN setelah preprocessing:")
print(df.isnull().sum())

# 5. Pisahkan fitur (X) dan target (y)
X = df.drop('Class', axis=1)
y = df['Class']

# 6. Bagi data training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Jumlah NaN setelah preprocessing:
pH               0
Temp             0
TSS              0
DO               0
BOD              0
COD              0
Nitrat           0
FecalColiform    0
Fosfat           0
IP               0
Class            0
dtype: int64


In [37]:
# 7. Normalisasi data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 8. Pastikan tidak ada NaN setelah scaling
print("\nJumlah NaN di X_train_scaled:", np.isnan(X_train_scaled).sum())
print("Jumlah NaN di X_test_scaled:", np.isnan(X_test_scaled).sum())

# 9. Buat dan latih model
model = LogisticRegression(
    max_iter=5000,
    solver='lbfgs',
    multi_class='multinomial',
    random_state=42
)
model.fit(X_train_scaled, y_train)
y_pred_proba = model.predict_proba(X_test_scaled)  # Probabilitas per kelas

# 10. Prediksi dan evaluasi
y_pred = model.predict(X_test_scaled)
print("\nAkurasi:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Jumlah NaN di X_train_scaled: 0
Jumlah NaN di X_test_scaled: 0

Akurasi: 0.958
Classification Report:
               precision    recall  f1-score   support

           1       0.96      0.94      0.95       196
           2       0.96      0.97      0.96       294
           3       1.00      0.83      0.91         6
           4       1.00      1.00      1.00         4

    accuracy                           0.96       500
   macro avg       0.98      0.94      0.96       500
weighted avg       0.96      0.96      0.96       500



/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [41]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
auc = roc_auc_score(y_test, y_pred_proba, multi_class='ovr', average='weighted')  # AUC untuk multiclass

print(f"Akurasi: {accuracy:.2f}")
print(f"Presisi: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")
print(f"AUC-ROC: {auc:.2f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))



Akurasi: 0.96
Presisi: 0.96
Recall: 0.96
F1-Score: 0.96
AUC-ROC: 1.00

Classification Report:
              precision    recall  f1-score   support

           1       0.96      0.94      0.95       196
           2       0.96      0.97      0.96       294
           3       1.00      0.83      0.91         6
           4       1.00      1.00      1.00         4

    accuracy                           0.96       500
   macro avg       0.98      0.94      0.96       500
weighted avg       0.96      0.96      0.96       500

Confusion Matrix:
[[184  12   0   0]
 [  8 286   0   0]
 [  0   1   5   0]
 [  0   0   0   4]]
